localities_list = [
	"Arroyo Verde",
	"Puerto Madryn",
	"Puerto Piramide",
	"Quinta el Mirador",
	"Reserva Area Protegida el Doradillo",
	"Buenos Aires Chico",
	"Cholila",
	"Comodoro Rivadavia",
	"Costa de Chubut",
	"Cushamen",
	"El Hoyo",
	"El Maiten",
	"Epuyen",
	"Fofo Cahuel",
	"Gualjaina",
	"Lago Epuyen",
	"Lago Puelo",
	"Leleque",
	"Astra",
	"Bahia Bustamante",
	"Diadema Argentina",
	"Rada Tilly",
	"Camarones",
	"Garayalde",
	"Aldea Escolar",
	"Corcovado",
	"Esquel",
	"Lago Rosario",
	"Los Cipreses",
	"Trevelin",
	"Villa Futalaufquen",
	"Dique Florentino Ameghino",
	"Dolavon",
	"Gaiman",
	"28 de julio",
	"Blancuntre",
	"El Escorial",
	"Gastre",
	"Lagunita Salada",
	"Yala Laubat",
	"Aldea Epulef",
	"Carrenleufu",
	"Colan Conhue",
	"Paso del Sapo",
	"Tecka",
	"El Mirasol",
	"Las Plumas",
	"Cerro Condor",
	"Los Altares",
	"Paso de Indios",
	"Playa Magagna",
	"Playa Unión",
	"Rawson",
	"Trelew",
	"Aldea Apeleg",
	"Aldea Beleiro",
	"Alto Rio Senguer",
	"Doctor Ricardo Rojas",
	"Facundo",
	"Lago Nlanco",
	"Rio Mayo",
	"Buen Pasto",
	"Sarmiento",
	"Frontera de Rio Pico",
	"Gobernador Costa",
	"Jose de San Martin",
	"Rio Pico",
	"Gan Gan",
	"Telsen",
]

localities_list.each do |nombre|
	Locality.find_or_create_by(name:nombre)
end