localities_list = [
	"Arroyo Verde",
	"Puerto Madryn",
	"Puerto Pirámides",
	"Quinta El Mirador",
	"Reserva Área Protegida el Doradillo",
	"Buenos Aires Chico",
	"Cholila",
	"Comodoro Rivadavia",
	"Costa de Chubut",
	"Cushamen",
	"El Hoyo",
	"El Maitén",
	"Epuyén",
	"Fofo Cahuel",
	"Gualjaina",
	"Lago Epuyén",
	"Lago Puelo",
	"Leleque",
	"Astra",
	"Bahía Bustamante",
	"Diadema Argentina",
	"Rada Tilly",
	"Camarones",
	"Garayalde",
	"Aldea Escolar",
	"Corcovado",
	"Esquel",
	"Lago Rosario",
	"Los Cipreses",
	"Trevelin",
	"Villa Futalaufquen",
	"Dique Florentino Ameghino",
	"Dolavon",
	"Gaiman",
	"28 de julio",
	"Blancuntre",
	"El Escorial",
	"Gastre",
	"Lagunita Salada",
	"Yala Laubat",
	"Aldea Epulef",
	"Carrenleufú",
	"Colan Conhué",
	"Paso del Sapo",
	"Tecka",
	"El Mirasol",
	"Las Plumas",
	"Cerro Cóndor",
	"Los Altares",
	"Paso de Indios",
	"Playa Magagna",
	"Playa Unión",
	"Rawson",
	"Trelew",
	"Aldea Apeleg",
	"Aldea Beleiro",
	"Alto Río Senguer",
	"Doctor Ricardo Rojas",
	"Facundo",
	"Lago Blanco",
	"Río Mayo",
	"Buen Pasto",
	"Sarmiento",
	"Frontera de Río Pico",
	"Gobernador Costa",
	"José de San Martín",
	"Río Pico",
	"Gan Gan",
	"Telsen",
]

localities_list.each do |nombre|
	Locality.find_or_create_by(name:nombre)
end


population_groups_list = [
	"Personas mayores de 60 años",
	"Personas entre 18 y 59 años con enfermedades preexistentes",
	"Personal de salud",
	"Personal de seguridad",
	"Personal docente y auxiliares"
]

population_groups_list.each do |descripción|
	PopulationGroup.find_or_create_by(description:descripción)
end

